"""init migration"""

revision = '3e18f3df8288'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa



def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promo_codes',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('discount_type', sa.String(length=20), nullable=False),
    sa.Column('discount_value', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('min_order_amount', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('rules_json', sa.JSON(), nullable=False),
    sa.Column('max_usages_per_user', sa.Integer(), nullable=True),
    sa.Column('total_max_usages', sa.Integer(), nullable=True),
    sa.Column('venue_id', sa.BIGINT(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_promo_codes')),
    schema='public'
    )
    op.create_index(op.f('ix_public_promo_codes_code'), 'promo_codes', ['code'], unique=True, schema='public')
    op.create_index(op.f('ix_public_promo_codes_venue_id'), 'promo_codes', ['venue_id'], unique=False, schema='public')
    op.create_table('payments',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.BIGINT(), nullable=False),
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('transaction_id', sa.String(length=255), nullable=False),
    sa.Column('payment_gateway', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('refunded_amount', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SUCCEEDED', 'FAILED', 'REFUNDED', 'PARTIALLY_REFUNDED', name='payment_status', schema='public'), nullable=False),
    sa.Column('payment_method', sa.Enum('BANK_CARD', 'SBP', name='payment_method', schema='public'), nullable=True),
    sa.Column('gateway_response', sa.JSON(), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('promo_code_id', sa.BIGINT(), nullable=True),
    sa.Column('discount_amount', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('refunded_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['promo_code_id'], ['public.promo_codes.id'], name=op.f('fk_payments_promo_code_id_promo_codes'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payments')),
    schema='public'
    )
    op.create_index(op.f('ix_public_payments_order_id'), 'payments', ['order_id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_payments_status'), 'payments', ['status'], unique=False, schema='public')
    op.create_index(op.f('ix_public_payments_transaction_id'), 'payments', ['transaction_id'], unique=True, schema='public')
    op.create_index(op.f('ix_public_payments_user_id'), 'payments', ['user_id'], unique=False, schema='public')
    op.create_table('promo_code_usages',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('promo_code_id', sa.BIGINT(), nullable=False),
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('order_id', sa.BIGINT(), nullable=True),
    sa.Column('payment_id', sa.BIGINT(), nullable=True),
    sa.Column('discount_applied', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['promo_code_id'], ['public.promo_codes.id'], name=op.f('fk_promo_code_usages_promo_code_id_promo_codes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_promo_code_usages')),
    schema='public'
    )
    op.create_index(op.f('ix_public_promo_code_usages_order_id'), 'promo_code_usages', ['order_id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_promo_code_usages_payment_id'), 'promo_code_usages', ['payment_id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_promo_code_usages_promo_code_id'), 'promo_code_usages', ['promo_code_id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_promo_code_usages_user_id'), 'promo_code_usages', ['user_id'], unique=False, schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_public_promo_code_usages_user_id'), table_name='promo_code_usages', schema='public')
    op.drop_index(op.f('ix_public_promo_code_usages_promo_code_id'), table_name='promo_code_usages', schema='public')
    op.drop_index(op.f('ix_public_promo_code_usages_payment_id'), table_name='promo_code_usages', schema='public')
    op.drop_index(op.f('ix_public_promo_code_usages_order_id'), table_name='promo_code_usages', schema='public')
    op.drop_table('promo_code_usages', schema='public')
    op.drop_index(op.f('ix_public_payments_user_id'), table_name='payments', schema='public')
    op.drop_index(op.f('ix_public_payments_transaction_id'), table_name='payments', schema='public')
    op.drop_index(op.f('ix_public_payments_status'), table_name='payments', schema='public')
    op.drop_index(op.f('ix_public_payments_order_id'), table_name='payments', schema='public')
    op.drop_table('payments', schema='public')
    op.drop_index(op.f('ix_public_promo_codes_venue_id'), table_name='promo_codes', schema='public')
    op.drop_index(op.f('ix_public_promo_codes_code'), table_name='promo_codes', schema='public')
    op.drop_table('promo_codes', schema='public')
    op.execute("DROP TYPE IF EXISTS public.payment_method")
    op.execute("DROP TYPE IF EXISTS public.payment_status")
    # ### end Alembic commands ###
